// File generated by flutterfire configure (manual setup).
// This file is safe to commit — it contains only public Firebase config keys.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxcwXrU2hrswPyvK5DSD7D8H1-YrYEuMU',
    appId: '1:372896158154:web:aa3f511252cc0e60593f33',
    messagingSenderId: '372896158154',
    projectId: 'krasnodar-travel',
    authDomain: 'krasnodar-travel.firebaseapp.com',
    storageBucket: 'krasnodar-travel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZFSCDcQEKLfKtJrNxdUEaUh5wkkUPzTM',
    appId: '1:372896158154:android:ef4598aa5dc3be4a593f33',
    messagingSenderId: '372896158154',
    projectId: 'krasnodar-travel',
    storageBucket: 'krasnodar-travel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbzdRwFXvgBVwzOGpnxIzCrTPUAOsRFrs',
    appId: '1:372896158154:ios:b2cb310c9abead7c593f33',
    messagingSenderId: '372896158154',
    projectId: 'krasnodar-travel',
    storageBucket: 'krasnodar-travel.firebasestorage.app',
    iosBundleId: 'com.krasnodartravel.app',
  );
}
